apiVersion: v1
kind: Service
metadata:
  name: node-todo-app-service
spec:
  type: LoadBalancer  # Use NodePort if running locally
  ports:
    - port: 80        # Port that will be exposed
      targetPort: 8000 # Port that the container listens on
  selector:
    app: node-todo-app
