name: Node.js CI/CD with Docker

on:
  push:
    branches:
      - master  # Trigger the workflow for push to master
  pull_request:
    branches:
      - master  # Trigger the workflow for PRs targeting master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Set the Node.js version you're using

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Run tests (if any)
    - name: Run tests
      run: npm test

    # Step 5: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t nagarajkhairate/todo-app:$GITHUB_SHA .
        docker tag nagarajkhairate/todo-app:$GITHUB_SHA nagarajkhairate/todo-app:latest

    # Step 6: Log in to Docker Hub using the credentials stored in GitHub Secrets
    - name: Log in to Docker Hub
      if: github.event_name == 'push'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    # Step 7: Push Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      if: github.event_name == 'push'
      run: |
        docker push nagarajkhairate/todo-app:$GITHUB_SHA
        docker push nagarajkhairate/todo-app:latest
